[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "texcleaner"
dynamic = ["version"]
description = "A GUI front-end for cleaning LaTeX track changes"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE", "THIRD_PARTY_NOTICES.md"]
authors = [
    {name = "Dan Shim"}
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "arxiv-latex-cleaner",
    "customtkinter>=6.0",
]

[project.optional-dependencies]
dev = [
    "build",
    "twine",
    "pytest",
]

packaging = [
    "pyinstaller>=6.0",
]

[project.scripts]
texcleaner = "texcleaner.__main__:main"

[project.urls]
Homepage = "https://github.com/shdshim/texcleaner"
Repository = "https://github.com/shdshim/texcleaner"
Issues = "https://github.com/shdshim/texcleaner/issues"

[tool.setuptools]
packages = ["texcleaner"]
package-data = {texcleaner = ["scripts/**/*.py", "assets/icons/*.png", "assets/icons/*.ico", "assets/icons/*.icns"]}

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.dynamic]
version = {attr = "texcleaner.version.__version__"}
